# Generated by Django 5.0.2 on 2024-02-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agregar',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='agregar',
            name='contenido',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='contenido',
            field=models.TextField(max_length=200),
        ),
    ]
