# Generated by Django 4.2 on 2024-04-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_tema_detallepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetallePost',
        ),
    ]
